### PR TITLE
Changing logging level to higher level command and Enable cProfile

### PR DESCRIPTION
**Pull request by calmacx**

### CODE REVIEW

**Comment by calmacx** [comment]
hey @spco this PR also enables cProfile that works well to dump to a file `coconnect.prof` which I can use `snakeviz` on. I gather this is the way you would do things?

Can now be run as this:
```
coconnect --profile map run --rules rules.json input_data/ -np 1000
```

After doing it, I realised I could instead just do:
```
python3 -m cProfile -o profile.prof  -m coconnect.cli.cli map run --rules rules.json input_data/ 
```

Don't think there's any difference (?)

**Comment by spco** [comment]
So far as I'm aware they're identical - I've usually only ever used the latter syntax as I haven't integrated it into the build, but I don't mind doing so in this instance as it saves users having to remember the syntax or optional dependencies.

**Comment by spco** [comment]
Talking of which, you'll want to add `CProfileV` and `snakeviz` to `requirements.txt`?

**Comment by calmacx** [comment]
I'm not sure what cprofilev is? I was using CProfile which is native. 

Can add `snakeviz` to the requirements, it's not big and only has one extra dependency

**Comment by calmacx** [comment]
ok this one should be good @spco  - if you were getting spammed by me - it was me screwing up merging/squashing/rebasing.

One commit now, so is much cleaner.

**Comment by spco** [comment]
Good point, you won't need cProfileV.

**Review by spco — APPROVED** [review]
LGTM

**Pull request merged**
